-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 12:19:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ssafyenjoy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ssafyenjoy` ;

-- -----------------------------------------------------
-- Schema ssafyenjoy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssafyenjoy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ssafyenjoy` ;

-- -----------------------------------------------------
-- Table `ssafyenjoy`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`member` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`member` (
  `userId` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `userPwd` VARCHAR(45) NOT NULL,
  `emailId` VARCHAR(45) NOT NULL,
  `emailDomain` VARCHAR(45) NOT NULL,
  `joinDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

-- Jwt 로그인을 위해 이거 실행해야 해!!!
alter table member add column token varchar(1000) null default null after joinDate;
-- -----------------------------------------
-- Table `ssafyenjoy`.`comment`
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`comment` (
`articleNo` INT NOT NULL,
`commentNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `commentContent` VARCHAR(255) NOT NULL,
  `commentRegisterTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`commentNo`),
  INDEX `articleNo_idx` (`articleNo` ASC) VISIBLE,
  FOREIGN KEY (`articleNo`)
  REFERENCES `board` (`articleNo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ssafyenjoy`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`board`;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`board` (
  `articleNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `hit` INT ZEROFILL NOT NULL,
  `registerTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`articleNo`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `ssafyenjoy`.`member` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 11/16 이거 추가했습니다!
alter table board add column location varchar(45) null default null after content;
alter table board add column startDate varchar(100) null default null after location;
alter table board add column endDate varchar(100) null default null after startDate;

-- 11/21 BoardDto에 이미지 추가했습니다.
alter table board add column mainImg varchar(500) null default "https://i.ibb.co/c6GdLvZ/noImg.png" after endDate;
select *
    	from board
    	where userId = "hey"
    	order by articleNo
-- -----------------------------------------
-- Table `ssafyenjoy`.`img`
-- -----------------------------------------

-- 11/21 추가
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`img` (
  `userId` VARCHAR(45) NOT NULL,
  `profileImg` VARCHAR(500) NOT NULL default "https://i.ibb.co/hZPRfz0/dog.jpg",
  PRIMARY KEY (`userId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  FOREIGN KEY (`userId`)
  REFERENCES `ssafyenjoy`.`member` (`userId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from img;

-- -----------------------------------------
-- Table `ssafyenjoy`.`plan`
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`plan` (
  `planNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `memo` VARCHAR(255),
  `startDate` VARCHAR(45) NOT NULL,
  `endDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`planNo`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  FOREIGN KEY (`userId`)
  REFERENCES `member` (`userId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------
-- Table `ssafyenjoy`.`plandate` 날짜별 계획
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`plandate` (
  `dateNo` INT NOT NULL AUTO_INCREMENT,
  `planNo` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `dateMemo` VARCHAR(255),
  PRIMARY KEY (`dateNo`),
  INDEX `planNo_idx` (`planNo` ASC) VISIBLE,
  FOREIGN KEY (`planNo`)
  REFERENCES `plan` (`planNo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------
-- Table `ssafyenjoy`.`plantime` 시간별 계획
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`plantime` (
  `timeNo` INT NOT NULL AUTO_INCREMENT,
  `dateNo` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `timeMemo` VARCHAR(255),
  PRIMARY KEY (`timeNo`),
  INDEX `dateNo_idx` (`dateNo` ASC) VISIBLE,
  FOREIGN KEY (`dateNo`)
  REFERENCES `plandate` (`dateNo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------
-- Table `ssafyenjoy`.`Sido`
-- -----------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`sido` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`sido` (
  `sidoCode` INT NOT NULL,
  `sidoName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sidoCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssafyenjoy`.`Gugun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`gugun` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`gugun` (
  `gugunCode` INT NOT NULL,
  `gugunName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gugunCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssafyenjoy`.`Marker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`marker` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`marker` (
  `markerNo` INT NOT NULL AUTO_INCREMENT,
  `contentTypeId` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `addr1` VARCHAR(45) NOT NULL,
  `addr2` VARCHAR(45) NULL,
  `firstImage` VARCHAR(45) NULL,
  `readCount` INT NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`markerNo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use ssafyenjoy;

select * from board;

insert into board(userId, subject, content, hit) 
values("ssafy", "하이용ㅇㅇ", "바이하이하이하ㅣㅇ", 1);
insert into member
values('ssafy', '김싸피', '1234', 'ssafy', 'naver.com', '2023-11-03');

select * from member;
commit;

insert into board(articleNo, userId, subject, content, hit) 
values('11','ssafy','1111', '111', '11');

select * from board;

insert into sido(sidoCode, sidoName)
values('1', '2');

select * from sido;
